# Main settings
main_settings:
  # Text formatting.
  # LEGACY - color via & and hex &#
  # LEGACY_ADVANCED - improved legacy with support for &## hex format
  # MINIMESSAGE - color via <color>
  # MINIMESSAGE was added in newer versions (1.17+)
  serializer: LEGACY
  # Random teleport command (specified without /)
  rtp_command: 'rtp'
  # Aliases for the random teleport command
  rtp_aliases: ['randomteleport', 'msrandomteleport']
  # Default channel name.
  # The specified channel will be used as the main one when entering the /rtp command
  # If the channel is not specified - the player will need to enter the channel name manually
  default_channel: 'default'
  # Enable PlaceholderAPI support?
  papi_support: true
  # Send anonymous statistics (recommended not to disable)
  enable_metrics: true
  # Check for updates (recommended not to disable)
  update_checker: true
  # Proxy settings
  proxy:
    # Is proxy support enabled
    enabled: false
    # Server name in the network
    server_id: 'server1'

# Random teleport channels
# You can create your own channels based on the pre-made ones in the plugin
channels:
  # Base channel (permission to use - rtp.channel.channel_name i.e. in this case rtp.channel.default)
  default:
    # Name of the file where the channel configuration will be located. (This file must be present in the channels folder)
    # If the name is not specified - configuration is done in the config itself (similar to deluxemenus)
    file: 'default.yml'
  # Channel that will teleport the player near other players
  # Teleport distance varies from 30 to 60 blocks from the player
  near:
    # You can put all settings in this config if it's easier for you.
    file: 'near.yml'
  # Channel that will teleport the player near regions
  # Teleport distance varies from 30 to 60 blocks from the player
  base:
    file: 'base.yml'

# Plugin messages (messages from prefix to fail_to_find_location can be applied to channels)
# Hex format - &#IIIDDD
# If you want to disable a message - specify ''
messages:
  prefix: '&7&l(&5&lMSTRandomTeleport&7&l) &6Â»&r'
  # The following messages can also be applied to channels
  no_perms: '%prefix% &cYou do not have permission to use this channel.'
  invalid_world: '%prefix% &fYou cannot use this random teleport channel in this world.'
  not_enough_players: '%prefix% &cThere are not enough players on the server to teleport via this channel. Required: &6%required% players.'
  not_enough_money: '%prefix% &cYou do not have enough money to teleport via this channel. Cost: &6%required% coins.'
  not_enough_hunger: '%prefix% &cYou do not have enough hunger points to teleport via this channel. Required: &6%required%.'
  not_enough_experience: '%prefix% &cYou do not have enough experience points to teleport via this channel. Required: &6%required%.'
  cooldown: '%prefix% &fYou cannot teleport via this channel yet. Please wait &6%time%'
  moved_on_teleport: '%prefix% &cYou moved! Teleportation cancelled.'
  teleported_on_teleport: '%prefix% &cYou teleported during RTP! Teleportation cancelled.'
  damaged_on_teleport: '%prefix% &cYou took damage! Teleportation cancelled.'
  damaged_other_on_teleport: '%prefix% &cYou dealt damage! Teleportation cancelled.'
  fail_to_find_location: '%prefix% &6Failed to find a suitable location. Please try again later!'
  # Command messages
  incorrect_channel: '%prefix% &cThe specified random teleport channel does not exist!'
  channel_not_specified: '%prefix% &cYou must specify a random teleport channel!'
  canceled: '%prefix% &aTeleportation cancelled!'
  # PlaceholderAPI placeholders
  placeholders:
    no_cooldown: '&aNo cooldown!'
    no_value: '&cNot available'
    # Time placeholders
    time:
      hours: ' h '
      minutes: ' m '
      seconds: ' s '
  # Admin commands section
  admin:
    reload: '%prefix% &aPlugin successfully reloaded!'
    unknown_argument: '%prefix% &cYou entered an invalid argument(s) to the command!'
    player_not_found: '%prefix% &cThe specified player was not found!'
    admin_help: |-
      %prefix% Admin commands help.
      &a/rtp admin reload &f- reload the plugin
      &a/rtp admin forceteleport <player> <channel> &8<force> &f- teleport a player via the specified channel
  # Console messages
  console:
    worldguard_connected: '&5WorldGuard connected!'
    economy_connected: '&6Economy connected!'
    permissions_connected: '&aPermissions manager connected!'
    placeholders_connected: '&ePlaceholders connected!'
    must_be_player: 'You must be a player!'
    debug_toggled: '&7Debug toggled to: &%status%%value%'
    update_check_complete: '&aUpdate check completed. Version: &b%version%'
    download_progress: '&aDownloading: &e%downloaded%KB&7/&e%total%KB &7(&e%percentage%&7%)'
    channel_skipped_no_worldguard: '&cChannel &e\'%channel%\' &cuses type NEAR_REGION, but WorldGuard is not installed! Channel will be skipped.'
    near_region_no_worldguard: '&cAttempt to use NEAR_REGION channel without WorldGuard for player &e%player%&c. Teleportation cancelled.'
    update_check:
      latest: '&aYou are using the latest version of the plugin!'
      outdated: '&aYou are using an outdated version of the plugin!'
      download_here: '&aYou can download the new version here:'
      update_command: '&aOr update the plugin using &b/rtp admin update'
  